#2 C commit

diff --git a/.github/workflows/dev-deploy.yaml b/.github/workflows/dev-deploy.yaml
--- a/.github/workflows/dev-deploy.yaml
+++ b/.github/workflows/dev-deploy.yaml
@@ -100,7 +100,7 @@ jobs:
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
           echo "Logging in to Docker..."
-          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin || { echo "Docker login failed"; exit 1; }
+          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin || { echo "Docker login failed"; exit 1; }
      
       - name: Check Docker version
         run: docker --version
